version: '3'
services:
    web:
        build: .
        ports: 
            - "80:3000"
        volumes:
            - .:/usr/src/app
        depends_on:
            - redis
    ipfs:
        build: ipfs/
        volumes:
            - /tmp/ipfs-docker-staging:/export
            - /tmp/ipfs-docker-data:/data/ipfs
        ports:
            - 8080:8080
            - 4001:4001
            - 127.0.0.1:5001:5001
        # NOTE: THIS DISABLES LOGGING FOR THE IPFS SERVICE
        logging:
            driver: none
    redis:
        image: 'bitnami/redis:latest'
        restart: "always"
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
        ports:
            - '6379:6379'
        volumes:
            - /tmp/redis:/bitnami/redis/data
