version: '3'
services:
    web:
        build: .
        ports: 
            - "80:3000"
        volumes:
            - .:/usr/src/app
    ipfs:
        build: ipfs/
        volumes:
            - /tmp/ipfs-docker-staging:/export
            - /tmp/ipfs-docker-data:/data/ipfs
        ports:
            - 8080:8080
            - 4001:4001
            - 127.0.0.1:5001:5001
        # NOTE: THIS DISABLES LOGGING FOR THE IPFS SERVICE
        logging:
            driver: none
